### ISSUE TITLE
Checklist before moving to watson-developer-cloud

### ISSUE THREAD

**Issue by germanattanasio** [watson-virtual-agents/chat-widget#81]
## Tasks
- [x] Use `eslint` with 2 spaces indentation. Start with [this config](https://github.com/watson-developer-cloud/conversation-simple/blob/cleanup/.eslintrc.yml)
- [x] Some of the variables are PascalCase and should be renamed to camelCase. 
- [x] Add a [`CHANGELOG.md`](https://github.com/watson-developer-cloud/java-sdk/blob/master/CHANGELOG.md) file
- [x] Move examples to an `examples` folder at root level. Combine it with the existing [sample app](https://github.com/watson-virtual-agents/virtual-agent-dialog) 
- [x] Add a [`RELEASE.md`](https://github.com/watson-developer-cloud/java-sdk/blob/master/RELEASE.md)
- [x] Add code coverage badge. I recommend https://codecov.io/
- [x] The `dist` folder should only have 2 js files. The minimized and the normal compiled code. We don't need to have all the versions there.
- [x] JSdoc should be generated and updated on each commit using Travis. Every tag and branch should be documented. See http://watson-developer-cloud.github.io/node-sdk/  You can copy the process from [here](https://github.com/watson-developer-cloud/node-sdk/blob/master/jsdoc/publish.sh)

 CC: @nfriedly, @kognate

**Comment by ethanwinters** [comment]
@germanattanasio is Casper specifically required? I had been starting to write tests in a branch using webdriverio with an aim to plug into a service like browserstack (at some point after approval and yada yada). Just being able to test on PhantomJS seems far less useful to me.

**Comment by kognate** [comment]
FWIW  We've been using casperjs and if this code moves into our stable I would prefer the tests be written in casperjs (the QA engineers are all writing casper, too).  

if you've only been starting to write tests in webdriverio is it too late to change?      

What about PhantomJS seems to be 'far less useful' ?  I'm not familiar with webdriverio so it's not obvious to me what your referring too here.

**Comment by ethanwinters** [comment]
webdriverio (its selenium webdriver with socket support, just in case we decide to add any kind of real time socket stuff to the chat widget) so we can run the tests (using a service like browserstack.com) on multiple versions of IE, Firefox, Chrome, mobile devices, etc, rather than just off of one webkit version that no major browser actually uses directly anymore.

It is not too late to change, but I was hoping to get some broader device coverage.

**Comment by ethanwinters** [comment]
@germanattanasio regarding the PascalCase issue, are you referring to the capitalization of constructor functions? That's a fairly common practice in the JS world including the Google and Airbnb style guides.

**Comment by germanattanasio** [comment]
@ethanwinters we decided to use `casperjs` because it was easier to follow for people that never test a web app. I don't mind if you want to use `webdriverio` but it will limit the help you will get from people that contribute to our repositories and are used to write `casperjs`. In any case, you should use the best tool so if you need to do real-time socket stuff use `webdriverio`.

**Comment by germanattanasio** [comment]
@ethanwinters I couldn't find the PascalCase variable  so I'm gonna mark the checkbox as complete.

**Comment by ethanwinters** [comment]
@najimovi and I will discuss the pros and cons of us doing casper and update here.Thanks!

**Comment by ethanwinters** [comment]
We are going to move forward with selenium to be able to take advantage of testing more environments.

**Comment by najimovi** [comment]
@germanattanasio Ger, we've completed the changes above, could you please guide us on how we'd continue with the move to watson-developer-cloud?. Thx!

**Comment by germanattanasio** [comment]
I'm a little bit confused about the README

Can we have three simple steps like:
1. How to get the API keys I need
1. How to install the library
1. How to run it

### Step 1
Most of what you have but with 1 or 2 gif showing how the pages they need to go look like. We found in user studies that people get lost because they don't have any idea if they are in the right page or not... Specially around Bluemix, WDC, Marketplace...

### Step 2

Add the chat widget to your html page:
```html
<script src="https://unpkg.com/@watson-virtual-agent/chat-widget@1.2.11/dist/chat.min.js">
<script>
        window.IBMChat.init({
            el: 'ibm_element',
            baseURL: 'https://api.ibm.com/virtualagent/run/api/v1/',
            botID: '',              // replace with Bot ID
            XIBMClientID: '',       // replace with Client ID
            XIBMClientSecret: ''    // replace with Client Secret
        });
</script>
```

I don't think we want users to clone a repository which means they will get the latest version of the code.

What do you guys thing, @ethanwinters @najimovi ?

**Comment by najimovi** [comment]
sounds good to me, gonna update that and get back to you

**Comment by ethanwinters** [comment]
@germanattanasio new readme: https://github.com/watson-virtual-agents/chat-widget/tree/1.2.12

**Comment by germanattanasio** [comment]
That looks really good but you still ask users to clone the repository. You should point to the  entire app. If you use GitHub releases then point to the release you want them to download https://github.com/watson-virtual-agents/chat-widget/archive/1.2.11.tar.gz

If they always clone `master` it doesn't make sense to have releases.

**Comment by ethanwinters** [comment]
@germanattanasio You are 1000% right. In fact, there is no reason for them to clone the repo unless they are planning on contributing. I added instructions on building the project locally to contributing.md and re-worked the readme to be embedded script tag/npm install focused.

**Comment by germanattanasio** [comment]
Changes look good. I think this repo is ready so we should focus on the `client-sdk` now

**Comment by ethanwinters** [comment]
Agreed. I'm going to close out this issue and we will get started over there.
